version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
