name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - run: pm2 stop bot
      - name: Archive all artifacts
        uses: actions/upload-artifact@v2
        with:
          name: server-dependencies
          path: |
            ./.env
            ./database/index.sqlite
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - name: Downloading artifacts
        uses: actions/download-artifact@v2
        with:
          name: server-dependencies
      - run: pm2 start bot
